steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lke-pprd-image-factory-abcde/untrusted/lookout-base/bionic-cd:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lke-pprd-image-factory-abcde/untrusted/lookout-base/bionic-cd:latest']
images: ['gcr.io/lke-pprd-image-factory-abcde/untrusted/lookout-base/bionic-cd:latest']
